edgar-care/frontend

.eslintrc.yaml
package.json
yarn.lock

fix(linter): fix eslint config & dependencies

---

.eslintrc.yaml
.husky/pre-commit

Update lint config & pre-commit command

fix: husky-pre-commit

---

pages/index.tsx
pages/solutions.tsx
src/components/landingPage/NavBar.tsx

fix(landing page): change button and redirection to simul and connection

---

pages/_app.tsx
pages/connection/infos.tsx
pages/connection/login.tsx
pages/connection/signup.tsx
pages/simulation/doctor.tsx
src/components/pages/ProtectedPage.tsx
src/components/pages/UnprotectedPage.tsx
src/components/simulationPage/ChatBox.tsx
src/components/simulationPage/ChatMessageCard.tsx
src/contexts/chat.ts
src/libs/auth.ts
src/libs/chat.ts
src/types/SymptomsContextType.ts
src/types/SymptomsType.ts

Add the connection for the chat between the front and the algorithm

feat: add-chat-connection

---

pages/apk.tsx
pages/solutions.tsx
src/components/landingPage/NavBar.tsx

feat: add-page-to-download-apk

---

pages/app/patient/medical.tsx
src/components/pages/patient/medical/TreatmentCard.tsx

- Fix typo
- Fix padding into the medical page

fix: fix-typo

---

pages/_app.tsx
pages/app/patient/medical.tsx
pages/connection/infos.tsx
pages/simulation/infos.tsx
src/components/NumInput.tsx
src/components/pages/patient/NavBar.tsx

feat: add v.0.5.1

---

src/components/pages/patient/NavBar.tsx

Fix scrollbar on navbar in the patient app

feat: add v.0.5.2

---

pages/app/patient/documents.tsx
src/components/pages/patient/medical/modal/UpdateMedicalModal.tsx
src/components/pages/patient/medical/modal/UpdateModalNumberForm.tsx

fix: update infos

---

src/libs/auth.ts

Overflow sur l'email lors de la création d'un compte

fix: impossible connection when bad infos

---

src/components/Footer.tsx
src/components/pages/patient/DocumentCard.tsx

Fix some UI & UX for E²
**No clickup reference**

fix: add 0.5.4

---

pages/simulation/chat.tsx

[**HOTFIX**]
Fix typo
No clickup reference

hotfix: add v0.5.5

---

landing-pages/cypress/e2e/contactPage.cy.ts
landing-pages/cypress/e2e/doctorPage.cy.ts
landing-pages/cypress/e2e/footer.cy.ts
landing-pages/cypress/e2e/homePage.cy.ts
landing-pages/src/app/doctor/page.tsx
landing-pages/src/components/contactPage/ContactFormSection.tsx
landing-pages/src/components/doctorPage/DoctorSearchBox.tsx
landing-pages/src/components/doctorPage/DoctorSearchResponseBox.tsx
landing-pages/src/components/doctorPage/DoctorSearchResponseCard.tsx
landing-pages/src/components/navigation/footer/CustomerServiceSection.tsx
landing-pages/src/theme/index.ts
landing-pages/src/types/DoctorSearchData.ts
landing-pages/src/types/DoctorSearchResponse.ts
landing-pages/src/utils/searchDoctor.ts

Les patients doivent pouvoir trouver les médecins utilisant l’application edgar
[CU-860qv9wt8](https://app.clickup.com/t/860qv9wt8)

feat: landingPage - Doctor page

---

landing-pages/cypress/e2e/contactPage.cy.ts
landing-pages/src/components/NewsletterForm.tsx
landing-pages/src/components/contactPage/ContactFormSection.tsx
landing-pages/src/components/doctorPage/DoctorSearchBox.tsx
landing-pages/src/components/productPage/milestone/MilestoneDetails.tsx
landing-pages/src/components/productPage/milestone/MilestoneRoadmap.tsx
landing-pages/src/theme/components/formLabel.ts
landing-pages/src/theme/index.ts
landing-pages/src/utils/emailValidityChecker.ts
landing-pages/src/utils/sendContactForm.ts
landing-pages/src/utils/subscribeToNewsletter.ts

- Fix responsive on milestone section into product page
- Add max length characters for inputs
[CU-860qz6mzq](https://app.clickup.com/t/860qz6mzq)

fix: landingPage - Contact & Product pages

---

edgar-app/cypress/e2e/loginPage.cy.ts
edgar-app/cypress/e2e/signupPage.cy.ts
edgar-app/src/app/signup/content.tsx
edgar-app/src/app/signup/page.tsx
edgar-app/src/components/connectionPage/signup/ConnectionSignupFields.tsx
edgar-app/src/components/connectionPage/signup/ConnectionSignupInputs.tsx
edgar-app/src/utils/connection/onSubmitSignup.ts

Le patient doit pouvoir s’inscrire afin d’accéder à l’application
[CU-860r6cqnk](https://app.clickup.com/t/860r6cqnk)

feat: app - Signup page

---

edgar-app/cypress/e2e/mobile/onboarding/medicalInfoPage.cy.ts
edgar-app/src/app/dashboard/layout.tsx
edgar-app/src/utils/api/onboarding/onSubmitMedicalInfos.ts
edgar-app/src/utils/api/onboarding/onSubmitPersonalInfos.ts

Add api url for onboarding flow
[CU-865d29w6y](https://app.clickup.com/t/865d29w6y)
Please post additional comments in this section if you have them, otherwise delete it.

feat: app: Add API URL for Onboarding flow

---

edgar-app/src/components/dashboardPages/appointments/modals/UpdateAppointmentDrawer.tsx
edgar-app/src/components/dashboardPages/appointments/modals/UpdateAppointmentModal.tsx
edgar-app/src/components/onboardingPages/personal/OnboardingPersonalFields.tsx

- Change the format of birthdate data send to the backend
- Add search bar for doctor in update appointments

hotfix: app - Onboarding personal page

---

.github/workflows/CI-frontend-app.yaml
.github/workflows/CI-frontend-pro.yaml

- Update API URL for cypress tests into Github Actions
[CU-86bxzb7jc](https://app.clickup.com/t/86bxzb7jc)

feat: update API URL

---

landing-pages/src/app/application/page.tsx

- Update apk download url
[CU-860r6cq9j](https://app.clickup.com/t/860r6cq9j)

fix: landingPage - Update apk download URL

---

edgar-app/src/app/dashboard/content.tsx
edgar-app/src/components/dashboardPages/appointments/AppointmentCalendar.tsx
edgar-app/src/components/dashboardPages/home/ChatCard.tsx
edgar-app/src/components/dashboardPages/home/HomeAppointmentsCard.tsx

- Add the appointments card on the home page
[CU-86bxb9ttd](https://app.clickup.com/t/86bxb9ttd)

feat: app: Home appointments card

---

edgar-doctor/src/components/app/dashboardPages/appointments/AppointmentsCalendarCard.tsx

Little fix on the AppointmentsCalendarCard
[CU-862kjqyq0](https://app.clickup.com/t/862kjqyq0)

fix: pro - Dashboard Display Appointments

---

edgar-doctor/src/components/app/dashboardPages/patients/subViews/PatientsSubViewAppointments.tsx
edgar-doctor/src/components/app/dashboardPages/patients/subViews/PatientsSubViewManager.tsx

Display the appointments between a doctor and a patient
[CU-86bxb9v7q](https://app.clickup.com/t/86bxb9v7q)

feat: pro - Dashboard Patient Appointments

---

edgar-app/src/components/dashboardPages/appointments/AppointmentCard.tsx
edgar-app/src/components/dashboardPages/appointments/AppointmentDoctorCard.tsx
edgar-app/src/components/dashboardPages/appointments/AppointmentsCalendarCard.tsx
edgar-app/src/components/dashboardPages/appointments/CalendarAppointmentCard.tsx
edgar-doctor/src/components/app/dashboardPages/appointments/AppointmentSlots.tsx
edgar-doctor/src/components/app/dashboardPages/appointments/modals/UpdateAppointmentContent.tsx
edgar-doctor/src/components/app/dashboardPages/diagnostics/chat/DiagnosticLogs.tsx
edgar-doctor/src/components/app/dashboardPages/diagnostics/medicalInfo/DiagnosticMedicalInfo.tsx
edgar-doctor/src/services/request/slots.ts
edgar-doctor/src/store/types/slots.type.ts

- Some UI fix
[CU-86byvz7ud](https://app.clickup.com/t/86byvz7ud)

feat: fix UI

---

edgar-doctor/src/components/app/dashboardPages/patients/subViews/PatientsSubViewManager.tsx
edgar-doctor/src/components/app/dashboardPages/patients/subViews/chat/PatientsSubViewChat.tsx
edgar-doctor/src/components/app/dashboardPages/patients/subViews/medicalInfo/PatientsSubViewMedicalInfo.tsx

- Display the medical info of a patient
[CU-86bxb9vbu](https://app.clickup.com/t/86bxb9vbu)

feat: pro: Add patient medical info subview

---

edgar-doctor/src/components/app/dashboardPages/patients/subViews/deletePatient/DeletePatientDrawer.tsx
edgar-doctor/src/components/app/dashboardPages/patients/subViews/deletePatient/DeletePatientHandler.tsx
edgar-doctor/src/components/app/dashboardPages/patients/subViews/deletePatient/DeletePatientModal.tsx
edgar-doctor/src/components/app/dashboardPages/patients/subViews/navigation/PatientsSubViewNavigation.tsx
edgar-doctor/src/components/app/dashboardPages/patients/subViews/navigation/PatientsSubViewNavigationHandler.tsx
edgar-doctor/src/services/request/patients.ts

- Remove a patient from the patient list
[CU-86bxb9w0y](https://app.clickup.com/t/86bxb9w0y)

feat: pro: Delete a patient

---

edgar-app/src/app/dashboard/layout.tsx
edgar-app/src/services/apiService.ts

Add redirection to login page when a query return a 401 status error code
[CU-86bz100bz](https://app.clickup.com/t/86bz100bz)

feat: pro - Handle 401 return status

---

edgar-doctor/src/app/dashboard/layout.tsx
edgar-doctor/src/services/apiService.ts

Add redirection to login page when a query return a 401 status error code
[CU-86bz0zzyz](https://app.clickup.com/t/86bz0zzyz)

feat: app - Handle 401 return status

---

edgar-app/src/components/connectionPage/login/ConnectionLoginInputs.tsx
edgar-app/src/components/connectionPage/login/modal/ResetPasswordHandler.tsx
edgar-app/src/services/apiService.ts
edgar-app/src/services/request/account.ts
edgar-app/src/store/types/account.type.ts
edgar-app/src/types/login/ResetPasswordType.ts

Add a modal for the forget password
[CU-86bz0zzu3](https://app.clickup.com/t/86bz0zzu3)

feat: app - Dashboard Forget Password

---

edgar-doctor/src/components/settingsModals/ModalPages.tsx
edgar-doctor/src/components/settingsModals/pages/devices/SettingsDevicesPage.tsx

Add a modal page who display the connected devices
[CU-86bz100bd](https://app.clickup.com/t/86bz100bd)

feat: pro - Dashboard Display Connected Devices

---

edgar-app/src/services/request/account.ts
edgar-doctor/src/components/app/connectionPage/login/ConnectionLoginInputs.tsx
edgar-doctor/src/components/app/connectionPage/login/modal/ResetPasswordHandler.tsx
edgar-doctor/src/services/apiService.ts
edgar-doctor/src/services/request/account.ts
edgar-doctor/src/store/types/account.type.ts
edgar-doctor/src/types/app/login/ResetPasswordType.ts

Create a clickable text who open a modal. The modal need an email to reset password
[CU-86bz100bq](https://app.clickup.com/t/86bz100bq)

feat: pro - Dashboard Forget Password

---

edgar-app/src/components/settingsModals/ModalPages.tsx
edgar-app/src/components/settingsModals/pages/account/SettingsAccountBackupCodesActivationPage.tsx
edgar-app/src/components/settingsModals/pages/account/SettingsAccountBackupCodesGeneratePage.tsx
edgar-app/src/components/settingsModals/pages/account/SettingsAccountBackupCodesInfoPage.tsx
edgar-app/src/components/settingsModals/pages/account/settingsAccountPage.ts

Create Modal to generate new backup codes
[CU-86bz0zzk1](https://app.clickup.com/t/86bz0zzk1)

feat: app - Dashboard Generate Backup Codes

---

edgar-doctor/src/components/settingsModals/ModalPages.tsx
edgar-doctor/src/components/settingsModals/pages/account/SettingsAccountBackupCodesActivationPage.tsx
edgar-doctor/src/components/settingsModals/pages/account/SettingsAccountBackupCodesGeneratePage.tsx
edgar-doctor/src/components/settingsModals/pages/account/SettingsAccountBackupCodesInfoPage.tsx
edgar-doctor/src/components/settingsModals/pages/account/settingsAccountPage.ts

Create modal to check generated backup codes
[CU-86bz100bb](https://app.clickup.com/t/86bz100bb)

feat: pro - Dashboard Generate Backup Codes

---

edgar-app/src/services/request/2fa.ts
edgar-app/src/services/request/appointments.ts
edgar-app/src/services/request/devices.ts
edgar-app/src/services/request/doctor.ts
edgar-app/src/services/request/documents.ts
edgar-app/src/services/request/medicines.ts
edgar-app/src/services/request/treatments.ts
edgar-doctor/src/services/request/2fa.ts
edgar-doctor/src/services/request/appointments.ts
edgar-doctor/src/services/request/devices.ts
edgar-doctor/src/services/request/doctor.ts
edgar-doctor/src/services/request/medicines.ts
edgar-doctor/src/services/request/prescriptions.ts
edgar-doctor/src/services/request/slots.ts

- Handle null value instead of empty array from backend response
[CU-86c0fndme](https://app.clickup.com/t/86c0fndme)

feat: app & pro - Handle null value instead of empty array from backend response

---

edgar-app/src/app/reset-password/content.tsx
edgar-app/src/app/reset-password/page.tsx
edgar-app/src/components/connectionPage/login/modal/ResetPasswordHandler.tsx
edgar-app/src/components/connectionPage/reset-password/ResetPasswordBanner.tsx
edgar-app/src/components/connectionPage/reset-password/ResetPasswordFields.tsx
edgar-app/src/services/apiService.ts
edgar-app/src/services/request/account.ts
edgar-app/src/store/types/account.type.ts
edgar-app/src/types/login/ResetPasswordType.ts
edgar-app/src/types/password/MissingPasswordType.ts
edgar-app/src/types/password/ResetPasswordType.ts

Create a page to after receiving the mail you can reset your password
[CU-86bz0zzwm](https://app.clickup.com/t/86bz0zzwm)

feat: app - Dashboard Reset Password

---

edgar-app/src/components/dashboardPages/medical/medicine/MedicineCard.tsx
edgar-app/src/components/dashboardPages/medical/medicine/ReadonlyMedicineCard.tsx
edgar-app/src/components/dashboardPages/medical/modal/forms/medical/healthIssues/SelectHealthIssueMedicineInput.tsx
edgar-app/src/components/dashboardPages/medical/modal/forms/medical/medicine/MedicineCard.tsx
edgar-app/src/components/dashboardPages/medical/modal/forms/medical/medicine/ReadonlyMedicineCard.tsx
edgar-app/src/components/dashboardPages/treatments/TreatmentCard.tsx
edgar-app/src/components/dashboardPages/treatments/TreatmentDisplayCard.tsx
edgar-app/src/components/dashboardPages/treatments/modal/AddTreatmentMedicineInput.tsx
edgar-app/src/components/onboardingPages/medical/healthIssues/SelectHealthIssueMedicineInput.tsx
edgar-app/src/services/request/medicines.ts
edgar-app/src/store/types/medicines.type.ts
edgar-app/src/types/dashboard/medical/MedicineType.ts
edgar-app/src/utils/app/dashboard/medical/displayMedicineUnit.ts
edgar-app/src/utils/app/dashboard/medical/displayMedicineUsageUnit.ts

- Update medicines advanced selector value to include the dosage form of the medicines
- Update the display of the dosage form unit
- Update the request of the medicines to include the new additional informations
[CU-86c0j996e](https://app.clickup.com/t/86c0j996e)

feat: app - Update medicines informations

---

edgar-app/src/components/BetaWarningBanner.tsx
edgar-app/src/components/connectionPage/login/ConnectionLoginInputs.tsx
edgar-app/src/components/connectionPage/signup/ConnectionSignupInputs.tsx
edgar-app/src/components/onboardingPages/medical/OnboardingMedicalFields.tsx
edgar-app/src/components/onboardingPages/personal/OnboardingPersonalFields.tsx
edgar-app/src/components/simulationPages/chat/SimulationChat.tsx

- Add beta warning banner on signup, login, onboarding and simulation pages
[CU-86c0jh9g8](https://app.clickup.com/t/86c0jh9g8)

feat: app - Add beta warning banner

---

edgar-doctor/cypress/e2e/desktop/dashboard/navigation/navigation.cy.ts
edgar-doctor/cypress/e2e/mobile/dashboard/navigation/navigation.cy.ts
edgar-doctor/src/app/dashboard/content.tsx
edgar-doctor/src/app/dashboard/page.tsx
edgar-doctor/src/components/app/dashboardPages/appointments/AppointmentsCalendarCard.tsx
edgar-doctor/src/components/app/dashboardPages/diagnostics/DiagnosticCard.tsx
edgar-doctor/src/components/app/dashboardPages/home/HomeAppointmentsCard.tsx
edgar-doctor/src/components/app/dashboardPages/home/HomeChatCard.tsx
edgar-doctor/src/components/app/dashboardPages/home/HomeDiagnosticsCard.tsx
edgar-doctor/src/components/app/dashboardPages/home/HomeNextAppointmentsCard.tsx
edgar-doctor/src/components/navigation/Navbar.tsx

- Add home page content
- Update navbar index
[CU-86c0khqme](https://app.clickup.com/t/86c0khqme)

feat: pro - Add home page

---

edgar-doctor/cypress/e2e/desktop/connection/loginPage.cy.ts
edgar-doctor/cypress/e2e/mobile/connection/loginPage.cy.ts
edgar-doctor/src/app/login/content.tsx
edgar-doctor/src/app/signup/content.tsx
edgar-doctor/src/components/app/connectionPage/ConnectionEdgarCard.tsx
edgar-doctor/src/components/app/connectionPage/login/ConnectionLoginFields.tsx
edgar-doctor/src/components/app/connectionPage/signup/ConnectionSignupFields.tsx

Fix the size and the text for the connection/signup page.
[CU-862kkngtg](https://app.clickup.com/t/862kkngtg)

fix: pro - Login Fix Typo

---

edgar-app/src/components/simulationPages/chat/SimulationChat.tsx
edgar-doctor/src/components/app/dashboardPages/diagnostics/summary/DiagnosticSummary.tsx
edgar-doctor/src/store/types/diagnostics.type.ts
edgar-doctor/src/types/app/dashboard/diagnostics/DiagnosticSummaryType.ts

- Fix some typo
- Update display symptoms in diagnostic view

fix: add v1.6.1

---

edgar-app/cypress/e2e/desktop/onboarding/personalInfoPage.cy.ts
edgar-app/cypress/e2e/mobile/onboarding/personalInfoPage.cy.ts
edgar-app/src/app/Providers.tsx
edgar-app/src/app/dashboard/layout.tsx
edgar-app/src/app/login/content.tsx
edgar-app/src/app/onboarding/layout.tsx
edgar-app/src/app/reset-password/content.tsx
edgar-app/src/app/signup/content.tsx
edgar-app/src/app/simulation/layout.tsx
edgar-app/src/components/onboardingPages/OnboardingEdgarCard.tsx
edgar-app/src/components/onboardingPages/personal/OnboardingPersonalFields.tsx

- Update the behavior of the loading screen to avoid having flashing screen when redirecting
- Add default value on birthdate in onboarding page
[CU-86c0qnza3](https://app.clickup.com/t/86c0qnza3)

fix: app - Update onboarding behavior

---

edgar-doctor/src/components/app/dashboardPages/patients/subViews/deletePatient/DeletePatientHandler.tsx

Change the content of the modal.
[CU-86c0udrx6](https://app.clickup.com/t/86c0udrx6)

fix: pro - Fix Content Delete Patient

---

edgar-app/src/components/connectionPage/login/modal/ResetPasswordHandler.tsx
edgar-doctor/src/components/app/connectionPage/login/modal/ResetPasswordHandler.tsx

Display an error message when the email don't have the good format
[CU-86c0uew84](https://app.clickup.com/t/86c0uew84)

fix: pro & app - Fix Connections Invalid Email

---

edgar-doctor/src/components/app/dashboardPages/patients/subViews/prescriptions/PatientPrescriptionCard.tsx

Update Fontweight of the Text
[CU-86c0x0v0w](https://app.clickup.com/t/86c0x0v0w)

fix: pro - Dashboard Patients Fix Fontweight Ordonnance

---

edgar-app/src/components/dashboardPages/documents/modal/UpdateDocumentHandler.tsx

Just fix the good Illustration
[CU-86c0x04mq](https://app.clickup.com/t/86c0x04mq)

fix: app - Dashboard Document Fix Update Illustration

---

edgar-app/src/services/request/2fa.ts
edgar-app/src/services/request/devices.ts

Add some tags to autoreload the 2fa Mobile
[CU-86c0z3d8t](https://app.clickup.com/t/86c0z3d8t)

fix: app - Autoreload On 2fa Mobile

---

edgar-app/src/components/settingsModals/pages/account/SettingsAccountDeletePage.tsx
edgar-app/src/services/request/auth.ts

Update the bouton with the delete account request
[CU-86c12725f](https://app.clickup.com/t/86c12725f)

feat: app - Dashboard Delete Account

---

edgar-app/src/components/settingsModals/ModalPages.tsx
edgar-app/src/components/settingsModals/pages/account/SettingsAccountResetPasswordPage.tsx
edgar-app/src/components/settingsModals/pages/account/settingsAccountPage.ts
edgar-app/src/services/request/account.ts
edgar-app/src/store/types/account.type.ts
edgar-app/src/types/password/UpdatePasswordType.ts
edgar-doctor/src/components/settingsModals/ModalPages.tsx
edgar-doctor/src/components/settingsModals/pages/account/SettingsAccountResetPasswordPage.tsx
edgar-doctor/src/components/settingsModals/pages/account/settingsAccountPage.ts
edgar-doctor/src/services/request/account.ts
edgar-doctor/src/store/types/account.type.ts
edgar-doctor/src/types/app/login/UpdatePasswordType.ts

Add an update password modal
[CU-86c144gw6](https://app.clickup.com/t/86c144gw6)

feat: app/pro - add update password

---

edgar-doctor/src/components/app/connectionPage/signup/ConnectionSignupInputs.tsx
edgar-doctor/src/components/app/connectionPage/signup/ConnectionSignupRegister.tsx

Verify mail and password before step 2
[CU-86c146kbf](https://app.clickup.com/t/86c146kbf)

fix: pro - Check Credentials

---

edgar-app/src/components/AdvancedSelector.tsx
edgar-app/src/components/dashboardPages/treatments/AddTreatmentModalContent.tsx
edgar-doctor/src/components/AdvancedSelector.tsx
edgar-doctor/src/components/app/dashboardPages/patients/modal/healthIssues/treatments/AddTreatmentModalContent.tsx
edgar-doctor/src/components/app/dashboardPages/patients/subViews/prescriptions/modals/PatientAddPrescriptionModalContent.tsx

- Fix autocomplete component to fix issues with selecting items
[CU-86c20wxrw](https://app.clickup.com/t/86c20wxrw)

fix(components): update autocomplete component

---

edgar-app/src/components/AdvancedSelector.tsx
edgar-app/src/components/dashboardPages/treatments/AddTreatmentModalContent.tsx
edgar-doctor/src/components/AdvancedSelector.tsx
edgar-doctor/src/components/app/dashboardPages/patients/modal/healthIssues/treatments/AddTreatmentModalContent.tsx
edgar-doctor/src/components/app/dashboardPages/patients/subViews/prescriptions/modals/PatientAddPrescriptionModalContent.tsx
experience-edgar-app/src/app/start/content.tsx

fix: add v1.8.1
